"""initial schema

Revision ID: 90e501761d6c
Revises: 
Create Date: 2026-05-30 13:23:05.781851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90e501761d6c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brokers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('mc_number', sa.String(length=50), nullable=True),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brokers_company_name'), 'brokers', ['company_name'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'DISPATCHER', 'DRIVER', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plate_number', sa.String(length=50), nullable=False),
    sa.Column('make', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('fuel_consumption_mpg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('driver_id'),
    sa.UniqueConstraint('plate_number')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('broker_id', sa.Integer(), nullable=True),
    sa.Column('dispatcher_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('origin_address', sa.String(length=500), nullable=False),
    sa.Column('destination_address', sa.String(length=500), nullable=False),
    sa.Column('distance_miles', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rate_per_mile', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cargo_type', sa.String(length=255), nullable=True),
    sa.Column('weight_lbs', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pickup_date', sa.Date(), nullable=True),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ASSIGNED', 'IN_TRANSIT', 'DELIVERED', 'CANCELLED', name='order_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['broker_id'], ['brokers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dispatcher_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_table('calculations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('distance_miles', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rate_per_mile', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fuel_consumption_mpg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fuel_price_per_gallon', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.Column('gross_revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fuel_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('extra_costs_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_expenses', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_profit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('margin_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calculations_order_id'), 'calculations', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calculations_order_id'), table_name='calculations')
    op.drop_table('calculations')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_brokers_company_name'), table_name='brokers')
    op.drop_table('brokers')
    # ### end Alembic commands ###
